services:
  - type: web
    name: flutter-todo
    env: static
    buildCommand: flutter build web --release
    staticPublishPath: ./build/web
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false 