services:
  - type: web
    name: flutter-todo
    env: static
    buildCommand: |
      git clone https://github.com/flutter/flutter.git
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter precache
      flutter pub get
      flutter build web --release
    staticPublishPath: ./build/web
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false 