services:
  - type: web
    name: flutter-todo
    env: static
    buildCommand: |
      echo "Installing system dependencies..."
      sudo apt-get update
      sudo apt-get install -y curl unzip xz-utils zip libglu1-mesa
      echo "Current directory: $(pwd)"
      echo "Installing Flutter..."
      git clone https://github.com/flutter/flutter.git -b stable
      echo "Setting PATH..."
      export PATH="$PATH:$(pwd)/flutter/bin"
      echo "PATH is now: $PATH"
      echo "Verifying Flutter installation..."
      ./flutter/bin/flutter --version
      echo "Running Flutter commands..."
      cd to_do_list
      ../flutter/bin/flutter precache
      ../flutter/bin/flutter pub get
      ../flutter/bin/flutter build web --release
      echo "Build completed!"
      cp -r build/web/* ../build/web/
    staticPublishPath: ./build/web
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false 