services:
  - type: web
    name: flutter-todo
    env: static
    buildCommand: ./build.sh
    staticPublishPath: build/web
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false 